version: '3'
services:
    elasticsearch:
        image: elasticsearch:5.4.0-alpine
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - elk
        environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"

    logstash:
        build: ./images/logstash/
        depends_on:
            - elasticsearch 
        volumes:
            - "./logs/:/opt/"
            - "./images/logstash/pipeline/:/usr/share/logstash/pipeline/"
            - "./images/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
        environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        networks:
            - elk

    kibana-ui:
        image: kibana:5.4.3
        depends_on: 
            - elasticsearch
        ports: 
            - "5601:5601"
        networks:
            - elk

networks:
  elk:
    driver: bridge
